# Builds when a release is published.
name: Build Workflow

permissions: write-all

on:
  release:
    types:
      - published

jobs:
  run:
    name: Build Release Package
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: "1.11.x"
        no-spcomp-proxy: true

    - name: Setup Ninja Build
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.0

    - name: Build Files
      run: |
        python3 configure.py
        ninja

    - name: Build Package
      # the package generation should probably be part of the ninja script itself
      run: |
        pushd build
        7za a -r FF2R-Sandy-Abilities.zip scripting/ plugins/ gamedata/ translations/
        popd

    - name: Release
      uses: softprops/action-gh-release@master
      with:
        files: |
          ./build/FF2R-Sandy-Abilities.zip
          ./build/gamedata/ff2r.sandy.txt
